title: "Handahamé DIA"
description: "Handahamé DIA – Economic & Business Analytics Portfolio"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Language
locale: "en-US"

# Theme skin
minimal_mistakes_skin: "default"  # options: air, dark, contrast, default

# Author profile
author:
  name: "Handahamé DIA"
  avatar: "/assets/img/nny.jpg"
  bio: "Economist specialized in business performance, analytics & pricing"
  location: "France"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/handahame-dia/"

# Navigation
header_pages:
  - index.md
  - projects.md
  - about.md

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
